pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', 
                    credentialsId: 'github-creds', 
                    url: 'https://github.com/EmmanuelKibe/alx-backend-python'
            }
        }
        stage('Test') {
            steps {
                pythonVirtualenv(pythonHome: 'Python3') {
                    // This ensures pip looks for requirements.txt inside messaging_app
                    dir('messaging_app') { 
                        sh 'pip install -r requirements.txt'
                        sh 'pip install pytest pytest-django'
                        // The report is generated inside messaging_app/test-reports/
                        sh 'pytest --junitxml=test-reports/results.xml'
                    }
                }
            }
        }
    }
    post {
        always {
            junit 'messaging_app/messaging_app/test-reports/results.xml'
        }
    }
}