pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                // Checkout the code from GitHub
                git branch: 'main', 
                    credentialsId: 'github-creds', 
                    url: 'https://github.com/EmmanuelKibe/alx-backend-python'
            }
        }
        stage('Test') {
            steps {
                // We move into the subdirectory and run commands manually
                dir('messaging_app') {
                    sh '''
                        python3 -m venv venv
                        . venv/bin/activate
                        pip install -r requirements.txt
                        pip install pytest pytest-django
                        mkdir -p test-reports
                        pytest --junitxml=test-reports/results.xml
                    '''
                }
            }
        }
    }
    post {
        always {
            // Jenkins will look here for the report to visualize it
            junit 'messaging_app/messaging_app/test-reports/results.xml'
        }
    }
}